version: '3'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    image: jupyter_development
    ports:
    - "8888:8888"
    volumes:
    - .:/workdir


# docker-compose up
# http://localhost:8888/lab?